"""init

Revision ID: 27df111f8644
Revises: 
Create Date: 2025-12-09 13:53:27.584091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27df111f8644'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('disease_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('disease_id')
    )
    op.create_index(op.f('ix_diseases_disease_id'), 'diseases', ['disease_id'], unique=False)
    op.create_table('districts',
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(), nullable=False),
    sa.Column('province_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('district_id')
    )
    op.create_index(op.f('ix_districts_district_id'), 'districts', ['district_id'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.disease_id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('risk_levels',
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ),
    sa.PrimaryKeyConstraint('risk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_levels')
    op.drop_table('reports')
    op.drop_index(op.f('ix_districts_district_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_diseases_disease_id'), table_name='diseases')
    op.drop_table('diseases')
    # ### end Alembic commands ###
