"""longitudes lattitudes columns added

Revision ID: f671073e00be
Revises: 27df111f8644
Create Date: 2025-12-13 17:50:17.141252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f671073e00be'
down_revision: Union[str, Sequence[str], None] = '27df111f8644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('districts', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('districts', sa.Column('lattitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('districts', 'lattitude')
    op.drop_column('districts', 'longitude')
    # ### end Alembic commands ###
